// Topics/categories for Learn feed
export interface LearnTopic {
  id: string;
  label: string;
  icon: string;
  color: string;
}

export const LEARN_TOPICS: LearnTopic[] = [
  { id: 'dopamine', label: 'Dopamine', icon: '⚡', color: 'from-violet-500 to-purple-600' },
  { id: 'psychology', label: 'Psychology', icon: '🧠', color: 'from-pink-500 to-rose-600' },
  { id: 'habits', label: 'Habits', icon: '🔁', color: 'from-blue-500 to-indigo-600' },
  { id: 'science', label: 'Science', icon: '🔬', color: 'from-cyan-500 to-teal-600' },
  { id: 'health', label: 'Health & Fitness', icon: '💪', color: 'from-green-500 to-emerald-600' },
  { id: 'productivity', label: 'Productivity', icon: '⏰', color: 'from-amber-500 to-orange-600' },
  { id: 'self-improvement', label: 'Self Improvement', icon: '🚀', color: 'from-rose-500 to-red-600' },
  { id: 'money', label: 'Money', icon: '💰', color: 'from-yellow-500 to-amber-600' },
  { id: 'technology', label: 'Technology', icon: '💻', color: 'from-slate-500 to-gray-600' },
  { id: 'relationships', label: 'Relationships', icon: '❤️', color: 'from-red-500 to-pink-600' },
  { id: 'creativity', label: 'Creativity', icon: '🎨', color: 'from-fuchsia-500 to-purple-600' },
  { id: 'philosophy', label: 'Philosophy', icon: '💭', color: 'from-indigo-500 to-blue-600' },
  { id: 'history', label: 'History', icon: '📜', color: 'from-amber-600 to-yellow-700' },
];

// Card data for Learn feed
export interface LearnCard {
  id: string;
  topicId: string;
  title: string;
  content: string;
  fact?: string;
  tryThis?: string;
  imageUrl: string;
  gradient: string;
}

// Comprehensive card data with images - 8-10 cards per category
export const LEARN_CARDS: LearnCard[] = [
  // ==================== DOPAMINE (10 cards) ====================
  {
    id: 'dopa-1',
    topicId: 'dopamine',
    title: "Dopamine isn't pleasure.",
    content: "It's anticipation. Your brain fires harder BEFORE the reward than during it. This is why cravings feel so intense but fulfillment fades fast.",
    fact: "Dopamine spikes 400% higher in anticipation than during consumption.",
    imageUrl: "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=800&h=600&fit=crop",
    gradient: "from-violet-900/90 via-purple-900/80 to-background",
  },
  {
    id: 'dopa-2',
    topicId: 'dopamine',
    title: "Variable rewards hijack your brain.",
    content: "Unpredictable payoffs create the strongest dopamine loops. That's why scrolling is so hard to stop — you never know what's next.",
    fact: "Social media uses the same mechanism as slot machines.",
    tryThis: "Notice when you're scrolling 'just to see' — that's the loop.",
    imageUrl: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=600&fit=crop",
    gradient: "from-amber-900/90 via-orange-900/80 to-background",
  },
  {
    id: 'dopa-3',
    topicId: 'dopamine',
    title: "Your baseline matters more than spikes.",
    content: "High-stim activities spike dopamine then crash it below baseline. Low-stim activities raise your baseline without the crash.",
    fact: "It takes 2-4 hours to return to baseline after a big dopamine spike.",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop",
    gradient: "from-blue-900/90 via-indigo-900/80 to-background",
  },
  {
    id: 'dopa-4',
    topicId: 'dopamine',
    title: "Dopamine tolerance is real.",
    content: "Like any drug, your brain adapts. The same stimulus gives less response over time. You need more and more to feel the same.",
    fact: "Dopamine receptor density decreases with chronic overstimulation.",
    tryThis: "Take a 24-hour break from your most stimulating activity.",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
    gradient: "from-red-900/90 via-rose-900/80 to-background",
  },
  {
    id: 'dopa-5',
    topicId: 'dopamine',
    title: "Effort releases dopamine too.",
    content: "Healthy dopamine is tied to effort, not just reward. Working toward a goal releases dopamine throughout the journey, not just at the end.",
    fact: "The brain rewards effort when it's connected to meaning.",
    imageUrl: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800&h=600&fit=crop",
    gradient: "from-green-900/90 via-emerald-900/80 to-background",
  },
  {
    id: 'dopa-6',
    topicId: 'dopamine',
    title: "Novelty is a dopamine trigger.",
    content: "Your brain is wired to seek new experiences. The Coolidge Effect shows we're drawn to novelty even when current options are fine.",
    fact: "Each new post/video is a 'novel' stimulus triggering dopamine.",
    imageUrl: "https://images.unsplash.com/photo-1493612276216-ee3925520721?w=800&h=600&fit=crop",
    gradient: "from-orange-900/90 via-amber-900/80 to-background",
  },
  {
    id: 'dopa-7',
    topicId: 'dopamine',
    title: "Dopamine fasting works.",
    content: "Taking breaks from high-dopamine activities resets your reward sensitivity. Even a few hours of low-stim time can help.",
    fact: "Dopamine receptor density increases after periods of low stimulation.",
    tryThis: "Schedule a 2-hour 'dopamine detox' with no screens.",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop",
    gradient: "from-teal-900/90 via-cyan-900/80 to-background",
  },
  {
    id: 'dopa-8',
    topicId: 'dopamine',
    title: "Music triggers dopamine.",
    content: "That chill you get from music? That's dopamine. Music is one of the healthy ways to experience pleasure without the downsides.",
    fact: "Musical 'chills' correlate with dopamine release in the brain.",
    imageUrl: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&h=600&fit=crop",
    gradient: "from-purple-900/90 via-violet-900/80 to-background",
  },
  {
    id: 'dopa-9',
    topicId: 'dopamine',
    title: "Sunlight boosts dopamine.",
    content: "Morning sunlight exposure increases dopamine receptor expression. It's one reason why morning routines work so well.",
    fact: "Just 10-30 minutes of morning sun can improve mood all day.",
    tryThis: "Get outside within 30 minutes of waking up.",
    imageUrl: "https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?w=800&h=600&fit=crop",
    gradient: "from-yellow-900/90 via-orange-900/80 to-background",
  },
  {
    id: 'dopa-10',
    topicId: 'dopamine',
    title: "Anticipation can be savored.",
    content: "Instead of instant gratification, try delaying rewards. The anticipation itself becomes enjoyable and trains healthier dopamine patterns.",
    fact: "Delayed gratification strengthens prefrontal cortex function.",
    imageUrl: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=800&h=600&fit=crop",
    gradient: "from-indigo-900/90 via-blue-900/80 to-background",
  },

  // ==================== PSYCHOLOGY (10 cards) ====================
  {
    id: 'psych-1',
    topicId: 'psychology',
    title: "Your prefrontal cortex is your brake.",
    content: "It's the part of your brain that says 'wait' before you act. Every time you delay an impulse, you literally strengthen this muscle.",
    fact: "The prefrontal cortex isn't fully developed until age 25.",
    imageUrl: "https://images.unsplash.com/photo-1617791160505-6f00504e3519?w=800&h=600&fit=crop",
    gradient: "from-pink-900/90 via-rose-900/80 to-background",
  },
  {
    id: 'psych-2',
    topicId: 'psychology',
    title: "Naming emotions cuts their power.",
    content: "When you label what you feel, your amygdala calms down. This is called 'affect labeling' — awareness creates distance from the feeling.",
    fact: "Labeling reduces amygdala activity by up to 50%.",
    tryThis: "Next time you feel an urge, say: 'I notice I'm feeling...'",
    imageUrl: "https://images.unsplash.com/photo-1544027993-37dbfe43562a?w=800&h=600&fit=crop",
    gradient: "from-rose-900/90 via-pink-900/80 to-background",
  },
  {
    id: 'psych-3',
    topicId: 'psychology',
    title: "Your brain rewires itself.",
    content: "Every time you resist an urge, you strengthen new neural pathways. This is neuroplasticity — your brain literally changes shape based on behavior.",
    fact: "New neural pathways can form in as little as 21 days.",
    imageUrl: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&h=600&fit=crop",
    gradient: "from-emerald-900/90 via-green-900/80 to-background",
  },
  {
    id: 'psych-4',
    topicId: 'psychology',
    title: "The spotlight effect is real.",
    content: "You think people notice you more than they do. In reality, everyone is too busy thinking about themselves to judge you.",
    fact: "Studies show we overestimate how much others notice our flaws by 50%.",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop",
    gradient: "from-blue-900/90 via-indigo-900/80 to-background",
  },
  {
    id: 'psych-5',
    topicId: 'psychology',
    title: "Cognitive load depletes willpower.",
    content: "When your brain is tired from decisions, impulse control suffers. This is why evenings are hardest — decision fatigue is real.",
    fact: "Judges grant more parole after breaks than before.",
    tryThis: "Make important decisions in the morning.",
    imageUrl: "https://images.unsplash.com/photo-1541199249251-f713e6145474?w=800&h=600&fit=crop",
    gradient: "from-amber-900/90 via-orange-900/80 to-background",
  },
  {
    id: 'psych-6',
    topicId: 'psychology',
    title: "The Zeigarnik Effect.",
    content: "Unfinished tasks occupy mental space. Your brain keeps 'open loops' until they're closed. This is why starting is often hardest.",
    fact: "Writing tasks down 'closes the loop' and frees mental space.",
    imageUrl: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&h=600&fit=crop",
    gradient: "from-teal-900/90 via-cyan-900/80 to-background",
  },
  {
    id: 'psych-7',
    topicId: 'psychology',
    title: "Loss aversion drives behavior.",
    content: "Losing something feels twice as bad as gaining it feels good. This is why 'streaks' work — you don't want to lose progress.",
    fact: "We feel losses 2x more intensely than equivalent gains.",
    imageUrl: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=600&fit=crop",
    gradient: "from-red-900/90 via-rose-900/80 to-background",
  },
  {
    id: 'psych-8',
    topicId: 'psychology',
    title: "Confirmation bias is universal.",
    content: "We seek information that confirms what we already believe. To grow, actively seek out perspectives that challenge you.",
    fact: "This bias affects everyone, regardless of intelligence.",
    tryThis: "Read one thing today from a perspective you disagree with.",
    imageUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=800&h=600&fit=crop",
    gradient: "from-purple-900/90 via-violet-900/80 to-background",
  },
  {
    id: 'psych-9',
    topicId: 'psychology',
    title: "Self-compassion beats self-criticism.",
    content: "Being hard on yourself after failure makes you MORE likely to repeat it. Self-compassion creates psychological safety to change.",
    fact: "Self-compassion is linked to lower anxiety and depression.",
    imageUrl: "https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=800&h=600&fit=crop",
    gradient: "from-green-900/90 via-emerald-900/80 to-background",
  },
  {
    id: 'psych-10',
    topicId: 'psychology',
    title: "The peak-end rule.",
    content: "We judge experiences by their peak moment and how they end, not the average. End things well, and you'll remember them well.",
    fact: "A painful procedure feels better if it ends with less pain.",
    imageUrl: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=800&h=600&fit=crop",
    gradient: "from-indigo-900/90 via-blue-900/80 to-background",
  },

  // ==================== HABITS (10 cards) ====================
  {
    id: 'habit-1',
    topicId: 'habits',
    title: "Every habit has a trigger.",
    content: "Cue → Routine → Reward. Breaking habits means interrupting this loop. Most triggers are context-based: location, time, or emotion.",
    fact: "Most habits are triggered by context, not willpower.",
    tryThis: "Track what happens RIGHT BEFORE your urges for 3 days.",
    imageUrl: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&h=600&fit=crop",
    gradient: "from-blue-900/90 via-indigo-900/80 to-background",
  },
  {
    id: 'habit-2',
    topicId: 'habits',
    title: "The 21-day myth is wrong.",
    content: "Habit formation actually takes 18-254 days depending on complexity. The average is 66 days. Be patient with yourself.",
    fact: "Simple habits form faster than complex ones.",
    imageUrl: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&h=600&fit=crop",
    gradient: "from-teal-900/90 via-cyan-900/80 to-background",
  },
  {
    id: 'habit-3',
    topicId: 'habits',
    title: "Implementation intentions work.",
    content: "Saying 'I will [behavior] at [time] in [location]' makes you 2-3x more likely to follow through. Specificity beats motivation.",
    fact: "Vague plans lead to vague results.",
    tryThis: "Write: 'When I feel [urge], I will [new behavior].'",
    imageUrl: "https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop",
    gradient: "from-yellow-900/90 via-amber-900/80 to-background",
  },
  {
    id: 'habit-4',
    topicId: 'habits',
    title: "Habit stacking accelerates change.",
    content: "Attach new habits to existing ones. 'After I [current habit], I will [new habit].' This leverages existing neural pathways.",
    fact: "Piggybacking habits has higher success rates than standalone ones.",
    tryThis: "After I brush my teeth, I will [new habit].",
    imageUrl: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=600&fit=crop",
    gradient: "from-green-900/90 via-emerald-900/80 to-background",
  },
  {
    id: 'habit-5',
    topicId: 'habits',
    title: "Environment design beats willpower.",
    content: "Make good habits easy and bad habits hard. Removing friction for good behaviors is more effective than motivation.",
    fact: "People who appear disciplined often just have better environments.",
    tryThis: "Remove one trigger from your environment today.",
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop",
    gradient: "from-orange-900/90 via-amber-900/80 to-background",
  },
  {
    id: 'habit-6',
    topicId: 'habits',
    title: "Two-minute rule for starting.",
    content: "Scale any habit down to 2 minutes. 'Read before bed' becomes 'Read one page.' Starting is the hardest part.",
    fact: "Habits must be established before they can be improved.",
    imageUrl: "https://images.unsplash.com/photo-1513001900722-370f803f498d?w=800&h=600&fit=crop",
    gradient: "from-rose-900/90 via-pink-900/80 to-background",
  },
  {
    id: 'habit-7',
    topicId: 'habits',
    title: "Never miss twice.",
    content: "Missing one day doesn't break a habit. Missing two starts a new pattern. The rule: never miss twice in a row.",
    fact: "One slip doesn't erase progress — but repeated slips do.",
    imageUrl: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&h=600&fit=crop",
    gradient: "from-purple-900/90 via-violet-900/80 to-background",
  },
  {
    id: 'habit-8',
    topicId: 'habits',
    title: "Reward timing matters.",
    content: "Immediate rewards build habits faster than delayed ones. Add something enjoyable to the end of good habits.",
    fact: "The brain connects the last thing experienced with the behavior.",
    tryThis: "Pair a habit you need with something you enjoy after.",
    imageUrl: "https://images.unsplash.com/photo-1533227268428-f9ed0900fb3b?w=800&h=600&fit=crop",
    gradient: "from-amber-900/90 via-yellow-900/80 to-background",
  },
  {
    id: 'habit-9',
    topicId: 'habits',
    title: "Keystone habits have ripple effects.",
    content: "Some habits trigger other positive changes. Exercise often leads to better eating, better sleep, and more energy.",
    fact: "Focusing on one keystone habit can transform multiple areas.",
    imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop",
    gradient: "from-cyan-900/90 via-teal-900/80 to-background",
  },
  {
    id: 'habit-10',
    topicId: 'habits',
    title: "Tracking creates awareness.",
    content: "What gets measured gets managed. Simple tracking — even just checkmarks — increases follow-through significantly.",
    fact: "Habit tracking alone can double success rates.",
    tryThis: "Track just ONE habit on paper for 7 days.",
    imageUrl: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop",
    gradient: "from-indigo-900/90 via-blue-900/80 to-background",
  },

  // ==================== SCIENCE (10 cards) ====================
  {
    id: 'sci-1',
    topicId: 'science',
    title: "Urges peak at 90 seconds.",
    content: "Most cravings naturally fade after this time. If you can ride the wave for just 90 seconds, intensity drops dramatically.",
    fact: "Urge intensity drops 50% after just 10 seconds of delay.",
    tryThis: "Next urge: set a 90-second timer and just observe.",
    imageUrl: "https://images.unsplash.com/photo-1501139083538-0139583c060f?w=800&h=600&fit=crop",
    gradient: "from-teal-900/90 via-cyan-900/80 to-background",
  },
  {
    id: 'sci-2',
    topicId: 'science',
    title: "Sleep restores dopamine.",
    content: "Your dopamine receptors need rest to reset. One bad night of sleep = significantly reduced impulse control the next day.",
    fact: "7-9 hours restores dopamine receptor function overnight.",
    imageUrl: "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800&h=600&fit=crop",
    gradient: "from-indigo-900/90 via-blue-900/80 to-background",
  },
  {
    id: 'sci-3',
    topicId: 'science',
    title: "Your brain overestimates rewards.",
    content: "The anticipation is always better than the reality. When you track predictions vs. actual experience, cravings weaken.",
    fact: "Accurate predictions reduce addictive dopamine spikes.",
    imageUrl: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&h=600&fit=crop",
    gradient: "from-amber-900/90 via-yellow-900/80 to-background",
  },
  {
    id: 'sci-4',
    topicId: 'science',
    title: "Cortisol impairs decision-making.",
    content: "Stress hormones reduce prefrontal cortex function. Under stress, you're more likely to act on impulse, not reason.",
    fact: "Chronic stress literally shrinks the prefrontal cortex.",
    tryThis: "Address stress directly — it's affecting your self-control.",
    imageUrl: "https://images.unsplash.com/photo-1474418397713-7ede21d49118?w=800&h=600&fit=crop",
    gradient: "from-red-900/90 via-rose-900/80 to-background",
  },
  {
    id: 'sci-5',
    topicId: 'science',
    title: "The gut-brain connection is real.",
    content: "Your gut produces 95% of your serotonin. Gut health directly affects mood, anxiety, and even cravings.",
    fact: "The gut has its own nervous system with 100 million neurons.",
    imageUrl: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800&h=600&fit=crop",
    gradient: "from-green-900/90 via-emerald-900/80 to-background",
  },
  {
    id: 'sci-6',
    topicId: 'science',
    title: "Blue light disrupts sleep.",
    content: "Screens emit blue light that suppresses melatonin. Poor sleep = poor impulse control the next day.",
    fact: "Just 2 hours of evening screen use delays melatonin by 22%.",
    tryThis: "No screens 1 hour before bed. Use night mode if you must.",
    imageUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=600&fit=crop",
    gradient: "from-blue-900/90 via-indigo-900/80 to-background",
  },
  {
    id: 'sci-7',
    topicId: 'science',
    title: "Glucose depletion affects willpower.",
    content: "Self-control uses glucose. When blood sugar is low, willpower weakens. This is why hunger makes you irritable.",
    fact: "A small snack can restore self-control capacity.",
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=600&fit=crop",
    gradient: "from-orange-900/90 via-amber-900/80 to-background",
  },
  {
    id: 'sci-8',
    topicId: 'science',
    title: "Nature reduces stress hormones.",
    content: "Just 20 minutes in nature significantly lowers cortisol levels. Urban environments keep stress elevated.",
    fact: "Forest bathing (shinrin-yoku) is prescribed medicine in Japan.",
    tryThis: "Spend 20 minutes outside in a green space today.",
    imageUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop",
    gradient: "from-emerald-900/90 via-green-900/80 to-background",
  },
  {
    id: 'sci-9',
    topicId: 'science',
    title: "Mirror neurons shape behavior.",
    content: "Your brain mimics what it observes. Watching others act impulsively primes you to do the same. Choose your media wisely.",
    fact: "We unconsciously imitate the behaviors we observe most.",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop",
    gradient: "from-purple-900/90 via-violet-900/80 to-background",
  },
  {
    id: 'sci-10',
    topicId: 'science',
    title: "Heart rate variability predicts self-control.",
    content: "Higher HRV = better emotional regulation. Slow breathing increases HRV, which improves impulse control.",
    fact: "HRV can be trained through regular breathwork practice.",
    imageUrl: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&h=600&fit=crop",
    gradient: "from-pink-900/90 via-rose-900/80 to-background",
  },

  // ==================== HEALTH & FITNESS (10 cards) ====================
  {
    id: 'health-1',
    topicId: 'health',
    title: "Exercise naturally elevates dopamine.",
    content: "Physical activity raises your baseline dopamine without the crash. It's one of the healthiest ways to feel good.",
    fact: "30 minutes of exercise raises dopamine by 30% for 2+ hours.",
    tryThis: "Even a 10-minute walk can shift your state.",
    imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop",
    gradient: "from-green-900/90 via-emerald-900/80 to-background",
  },
  {
    id: 'health-2',
    topicId: 'health',
    title: "Cold exposure builds willpower.",
    content: "Deliberately choosing discomfort trains your brain to override impulses. Cold showers are a daily willpower workout.",
    fact: "Cold water increases dopamine by 250% for several hours.",
    imageUrl: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&h=600&fit=crop",
    gradient: "from-cyan-900/90 via-blue-900/80 to-background",
  },
  {
    id: 'health-3',
    topicId: 'health',
    title: "Slow breathing calms your nervous system.",
    content: "Your vagus nerve connects breath to brain. When you slow your breathing, your heart rate drops and cravings follow.",
    fact: "90 seconds of slow breathing can reset your nervous system.",
    tryThis: "Breathe in for 4, hold for 4, out for 8.",
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&h=600&fit=crop",
    gradient: "from-teal-900/90 via-emerald-900/80 to-background",
  },
  {
    id: 'health-4',
    topicId: 'health',
    title: "Hydration affects cognition.",
    content: "Even mild dehydration impairs concentration, mood, and decision-making. Most people are chronically under-hydrated.",
    fact: "2% dehydration reduces cognitive performance by 25%.",
    tryThis: "Drink a glass of water right now.",
    imageUrl: "https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=800&h=600&fit=crop",
    gradient: "from-blue-900/90 via-indigo-900/80 to-background",
  },
  {
    id: 'health-5',
    topicId: 'health',
    title: "Protein stabilizes mood.",
    content: "Amino acids from protein are building blocks for neurotransmitters. Low protein = unstable mood and energy.",
    fact: "Tryptophan from protein is needed to make serotonin.",
    imageUrl: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&h=600&fit=crop",
    gradient: "from-amber-900/90 via-orange-900/80 to-background",
  },
  {
    id: 'health-6',
    topicId: 'health',
    title: "Walking is underrated medicine.",
    content: "Walking reduces anxiety, boosts creativity, and improves mood. It's the most accessible form of exercise.",
    fact: "A 15-minute walk can reduce chocolate cravings by 50%.",
    tryThis: "Take a 10-minute walk when you feel an urge.",
    imageUrl: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&h=600&fit=crop",
    gradient: "from-green-900/90 via-teal-900/80 to-background",
  },
  {
    id: 'health-7',
    topicId: 'health',
    title: "Sleep debt compounds.",
    content: "You can't 'catch up' on sleep in one night. Chronic sleep deprivation accumulates and affects everything.",
    fact: "After 4 days of 6 hours sleep, you're as impaired as being drunk.",
    imageUrl: "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800&h=600&fit=crop",
    gradient: "from-indigo-900/90 via-purple-900/80 to-background",
  },
  {
    id: 'health-8',
    topicId: 'health',
    title: "Caffeine has a long half-life.",
    content: "Caffeine stays in your system longer than you think. That afternoon coffee is still affecting you at bedtime.",
    fact: "Caffeine's half-life is 5-6 hours. Half is still in you at midnight.",
    tryThis: "No caffeine after 2pm for a week. Notice the difference.",
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=600&fit=crop",
    gradient: "from-amber-900/90 via-yellow-900/80 to-background",
  },
  {
    id: 'health-9',
    topicId: 'health',
    title: "Posture affects psychology.",
    content: "How you hold your body affects how you feel. Expansive postures increase testosterone and decrease cortisol.",
    fact: "2 minutes of 'power posing' changes hormone levels measurably.",
    tryThis: "Sit up straight right now. Notice the shift.",
    imageUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop",
    gradient: "from-rose-900/90 via-pink-900/80 to-background",
  },
  {
    id: 'health-10',
    topicId: 'health',
    title: "Movement beats sitting.",
    content: "Prolonged sitting is linked to depression, anxiety, and poor focus. Regular movement breaks restore cognitive function.",
    fact: "Moving every 30 minutes reduces negative health effects by 80%.",
    tryThis: "Set a timer to move for 2 minutes every 30 minutes.",
    imageUrl: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&h=600&fit=crop",
    gradient: "from-emerald-900/90 via-green-900/80 to-background",
  },

  // ==================== PRODUCTIVITY (10 cards) ====================
  {
    id: 'prod-1',
    topicId: 'productivity',
    title: "Your attention is being mined.",
    content: "Apps are designed by the world's best engineers to capture and hold your focus. This isn't a fair fight — but awareness helps.",
    fact: "The average person touches their phone 2,617 times per day.",
    imageUrl: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=600&fit=crop",
    gradient: "from-red-900/90 via-orange-900/80 to-background",
  },
  {
    id: 'prod-2',
    topicId: 'productivity',
    title: "Multitasking is a myth.",
    content: "Your brain doesn't multitask — it rapidly switches. Each switch costs time and energy. Deep focus beats scattered attention.",
    fact: "Task switching can reduce productivity by up to 40%.",
    tryThis: "Try single-tasking for just one hour today.",
    imageUrl: "https://images.unsplash.com/photo-1483058712412-4245e9b90334?w=800&h=600&fit=crop",
    gradient: "from-orange-900/90 via-amber-900/80 to-background",
  },
  {
    id: 'prod-3',
    topicId: 'productivity',
    title: "Boredom is productive.",
    content: "When you're bored, your brain enters 'default mode' — the state where creativity and problem-solving happen.",
    fact: "Our best ideas often come during unfocused time.",
    imageUrl: "https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?w=800&h=600&fit=crop",
    gradient: "from-slate-900/90 via-gray-900/80 to-background",
  },
  {
    id: 'prod-4',
    topicId: 'productivity',
    title: "Deep work is rare and valuable.",
    content: "The ability to focus deeply on cognitively demanding tasks is becoming increasingly rare — and increasingly valuable.",
    fact: "Most knowledge workers get 90 minutes of deep work daily.",
    tryThis: "Block 90 minutes with no interruptions tomorrow.",
    imageUrl: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=600&fit=crop",
    gradient: "from-blue-900/90 via-indigo-900/80 to-background",
  },
  {
    id: 'prod-5',
    topicId: 'productivity',
    title: "Parkinson's Law is real.",
    content: "Work expands to fill the time available. Shorter deadlines often produce the same quality with less procrastination.",
    fact: "Self-imposed deadlines increase completion rates by 75%.",
    imageUrl: "https://images.unsplash.com/photo-1501139083538-0139583c060f?w=800&h=600&fit=crop",
    gradient: "from-purple-900/90 via-violet-900/80 to-background",
  },
  {
    id: 'prod-6',
    topicId: 'productivity',
    title: "First thing first.",
    content: "Do your most important task first, before distractions accumulate. Your willpower and focus are highest in the morning.",
    fact: "People who tackle hard tasks first report less stress overall.",
    tryThis: "Identify your MIT (Most Important Task) tonight for tomorrow.",
    imageUrl: "https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=800&h=600&fit=crop",
    gradient: "from-amber-900/90 via-orange-900/80 to-background",
  },
  {
    id: 'prod-7',
    topicId: 'productivity',
    title: "Energy management beats time management.",
    content: "It's not about finding more time — it's about matching tasks to your energy levels. Do creative work when energy is high.",
    fact: "Most people have 2-4 hours of peak cognitive performance daily.",
    imageUrl: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop",
    gradient: "from-green-900/90 via-emerald-900/80 to-background",
  },
  {
    id: 'prod-8',
    topicId: 'productivity',
    title: "The Pomodoro Technique works.",
    content: "25 minutes of focused work, then a 5-minute break. This rhythm prevents burnout and maintains focus.",
    fact: "Regular breaks actually increase total output.",
    tryThis: "Set a 25-minute timer for your next task.",
    imageUrl: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&h=600&fit=crop",
    gradient: "from-red-900/90 via-rose-900/80 to-background",
  },
  {
    id: 'prod-9',
    topicId: 'productivity',
    title: "Batching reduces switching costs.",
    content: "Group similar tasks together. Answer emails at set times, not continuously. This reduces context-switching overhead.",
    fact: "It takes 23 minutes to refocus after an interruption.",
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop",
    gradient: "from-cyan-900/90 via-teal-900/80 to-background",
  },
  {
    id: 'prod-10',
    topicId: 'productivity',
    title: "Saying no is saying yes to priorities.",
    content: "Every yes is a no to something else. Protecting your time means declining things that don't align with your goals.",
    fact: "Successful people say no to almost everything.",
    imageUrl: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=600&fit=crop",
    gradient: "from-indigo-900/90 via-blue-900/80 to-background",
  },

  // ==================== SELF IMPROVEMENT (10 cards) ====================
  {
    id: 'self-1',
    topicId: 'self-improvement',
    title: "Small wins compound.",
    content: "Don't aim for massive change. Tiny daily improvements of 1% lead to being 37x better in a year.",
    fact: "Consistency beats intensity for lasting change.",
    tryThis: "What's ONE tiny thing you can do today?",
    imageUrl: "https://images.unsplash.com/photo-1533227268428-f9ed0900fb3b?w=800&h=600&fit=crop",
    gradient: "from-rose-900/90 via-red-900/80 to-background",
  },
  {
    id: 'self-2',
    topicId: 'self-improvement',
    title: "Identity beats goals.",
    content: "Instead of 'I want to quit X', try 'I'm not someone who does X.' Identity-based change is more powerful than outcome-based.",
    fact: "Beliefs shape behavior more than willpower.",
    imageUrl: "https://images.unsplash.com/photo-1494972308805-463bc619d34e?w=800&h=600&fit=crop",
    gradient: "from-purple-900/90 via-violet-900/80 to-background",
  },
  {
    id: 'self-3',
    topicId: 'self-improvement',
    title: "Growth mindset is trainable.",
    content: "Believing you can improve is the first step to improving. Fixed mindset = 'I can't change.' Growth mindset = 'I can't do this yet.'",
    fact: "Students taught growth mindset improved grades significantly.",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop",
    gradient: "from-green-900/90 via-emerald-900/80 to-background",
  },
  {
    id: 'self-4',
    topicId: 'self-improvement',
    title: "Failure is data.",
    content: "Every failure teaches you something. The only true failure is not learning from it. Reframe setbacks as experiments.",
    fact: "Most successful people failed more times than most people tried.",
    tryThis: "Ask: 'What did this teach me?'",
    imageUrl: "https://images.unsplash.com/photo-1455849318743-b2233052fcff?w=800&h=600&fit=crop",
    gradient: "from-amber-900/90 via-orange-900/80 to-background",
  },
  {
    id: 'self-5',
    topicId: 'self-improvement',
    title: "Comfort zone is the danger zone.",
    content: "Growth happens at the edge of comfort. If you're comfortable, you're not growing. Seek productive discomfort.",
    fact: "Skills develop fastest when challenge slightly exceeds ability.",
    imageUrl: "https://images.unsplash.com/photo-1519834785169-98be25ec3f84?w=800&h=600&fit=crop",
    gradient: "from-red-900/90 via-rose-900/80 to-background",
  },
  {
    id: 'self-6',
    topicId: 'self-improvement',
    title: "Journaling is thinking on paper.",
    content: "Writing clarifies thought. Journaling helps process emotions, identify patterns, and problem-solve.",
    fact: "Expressive writing reduces anxiety and improves immunity.",
    tryThis: "Write for 5 minutes about what's on your mind.",
    imageUrl: "https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop",
    gradient: "from-blue-900/90 via-indigo-900/80 to-background",
  },
  {
    id: 'self-7',
    topicId: 'self-improvement',
    title: "You are the average of 5 people.",
    content: "The people you spend the most time with shape your thinking. Consciously choose who influences you.",
    fact: "Social influence affects habits, weight, even happiness levels.",
    imageUrl: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&h=600&fit=crop",
    gradient: "from-pink-900/90 via-rose-900/80 to-background",
  },
  {
    id: 'self-8',
    topicId: 'self-improvement',
    title: "Morning routines set the tone.",
    content: "How you start your day influences the rest of it. A intentional morning creates momentum for everything after.",
    fact: "90% of high performers have a consistent morning routine.",
    tryThis: "Design your first 30 minutes intentionally.",
    imageUrl: "https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?w=800&h=600&fit=crop",
    gradient: "from-yellow-900/90 via-amber-900/80 to-background",
  },
  {
    id: 'self-9',
    topicId: 'self-improvement',
    title: "Gratitude rewires your brain.",
    content: "Regularly noting what you're grateful for literally changes brain structure toward positivity.",
    fact: "3 weeks of gratitude practice measurably increases happiness.",
    tryThis: "Name 3 things you're grateful for right now.",
    imageUrl: "https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=800&h=600&fit=crop",
    gradient: "from-emerald-900/90 via-green-900/80 to-background",
  },
  {
    id: 'self-10',
    topicId: 'self-improvement',
    title: "Action precedes motivation.",
    content: "Don't wait to feel motivated. Start anyway. Motivation often follows action, not the other way around.",
    fact: "The hardest part of most tasks is the first 5 minutes.",
    imageUrl: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800&h=600&fit=crop",
    gradient: "from-teal-900/90 via-cyan-900/80 to-background",
  },

  // ==================== MONEY (8 cards) ====================
  {
    id: 'money-1',
    topicId: 'money',
    title: "Hedonic adaptation applies to money too.",
    content: "The happiness boost from more money fades quickly. After basic needs are met, experiences beat possessions.",
    fact: "Above ~$75K/year, more money doesn't increase daily happiness.",
    imageUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=600&fit=crop",
    gradient: "from-yellow-900/90 via-amber-900/80 to-background",
  },
  {
    id: 'money-2',
    topicId: 'money',
    title: "Time > Money for happiness.",
    content: "People who value time over money report higher life satisfaction. You can always make more money, never more time.",
    fact: "Buying time (outsourcing chores) increases happiness.",
    imageUrl: "https://images.unsplash.com/photo-1579621970795-87facc2f976d?w=800&h=600&fit=crop",
    gradient: "from-green-900/90 via-emerald-900/80 to-background",
  },
  {
    id: 'money-3',
    topicId: 'money',
    title: "Compound interest is magical.",
    content: "Small amounts saved early grow exponentially. Starting at 25 vs 35 can mean twice as much at retirement.",
    fact: "Einstein allegedly called compound interest the 8th wonder of the world.",
    tryThis: "Automate even $50/month into savings.",
    imageUrl: "https://images.unsplash.com/photo-1518458028785-8fbcd101ebb9?w=800&h=600&fit=crop",
    gradient: "from-blue-900/90 via-indigo-900/80 to-background",
  },
  {
    id: 'money-4',
    topicId: 'money',
    title: "Lifestyle creep is real.",
    content: "As income rises, spending tends to rise with it. Keeping lifestyle fixed as income grows accelerates wealth.",
    fact: "Most lottery winners end up poorer than before within 5 years.",
    imageUrl: "https://images.unsplash.com/photo-1459257831348-f0cdd359235f?w=800&h=600&fit=crop",
    gradient: "from-rose-900/90 via-pink-900/80 to-background",
  },
  {
    id: 'money-5',
    topicId: 'money',
    title: "Experiences beat possessions.",
    content: "Money spent on experiences creates more lasting happiness than things. Memories appreciate; stuff depreciates.",
    fact: "Anticipation of experiences creates happiness even before they happen.",
    imageUrl: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&h=600&fit=crop",
    gradient: "from-teal-900/90 via-cyan-900/80 to-background",
  },
  {
    id: 'money-6',
    topicId: 'money',
    title: "Financial stress affects everything.",
    content: "Money worries occupy mental bandwidth. Financial security reduces stress and frees cognitive resources.",
    fact: "Financial stress can reduce effective IQ by 13 points.",
    imageUrl: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=600&fit=crop",
    gradient: "from-red-900/90 via-orange-900/80 to-background",
  },
  {
    id: 'money-7',
    topicId: 'money',
    title: "Spending reveals values.",
    content: "Where your money goes shows what you truly value. Track spending to see if it aligns with stated priorities.",
    fact: "Most people can't accurately estimate their monthly spending.",
    tryThis: "Track every purchase for one week.",
    imageUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=600&fit=crop",
    gradient: "from-purple-900/90 via-violet-900/80 to-background",
  },
  {
    id: 'money-8',
    topicId: 'money',
    title: "The latte factor is real.",
    content: "Small daily expenses add up to shocking annual totals. $5/day = $1,825/year = $18,250 in a decade.",
    fact: "Tracking small purchases often reveals easy cuts.",
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=600&fit=crop",
    gradient: "from-amber-900/90 via-yellow-900/80 to-background",
  },

  // ==================== TECHNOLOGY (8 cards) ====================
  {
    id: 'tech-1',
    topicId: 'technology',
    title: "Notifications are designed to hook you.",
    content: "Every red badge, every buzz is engineered to trigger a dopamine response. Turn off non-essential notifications.",
    fact: "The average person receives 46 push notifications per day.",
    tryThis: "Turn off all non-essential notifications for 24 hours.",
    imageUrl: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&h=600&fit=crop",
    gradient: "from-slate-900/90 via-gray-900/80 to-background",
  },
  {
    id: 'tech-2',
    topicId: 'technology',
    title: "Infinite scroll is intentional.",
    content: "There's no natural stopping point because that's how they keep you scrolling. Add friction: set time limits.",
    fact: "People scroll an average of 300 feet per day on their phones.",
    imageUrl: "https://images.unsplash.com/photo-1605106702734-205df224ecce?w=800&h=600&fit=crop",
    gradient: "from-blue-900/90 via-indigo-900/80 to-background",
  },
  {
    id: 'tech-3',
    topicId: 'technology',
    title: "Algorithms create filter bubbles.",
    content: "AI shows you more of what you engage with. This can create echo chambers and distort your view of reality.",
    fact: "Algorithms optimize for engagement, not for your wellbeing.",
    tryThis: "Actively seek out diverse perspectives.",
    imageUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=600&fit=crop",
    gradient: "from-purple-900/90 via-violet-900/80 to-background",
  },
  {
    id: 'tech-4',
    topicId: 'technology',
    title: "Screen time is tracked for a reason.",
    content: "Phones now show you screen time because usage patterns surprised even designers. Check your stats.",
    fact: "Average screen time is 7+ hours per day for adults.",
    imageUrl: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=600&fit=crop",
    gradient: "from-red-900/90 via-rose-900/80 to-background",
  },
  {
    id: 'tech-5',
    topicId: 'technology',
    title: "Grayscale reduces phone appeal.",
    content: "Color triggers dopamine. Switching your phone to grayscale makes it less stimulating and easier to put down.",
    fact: "Some users report 50% reduction in usage with grayscale.",
    tryThis: "Try grayscale mode for one day.",
    imageUrl: "https://images.unsplash.com/photo-1522199755839-a2bacb67c546?w=800&h=600&fit=crop",
    gradient: "from-gray-900/90 via-slate-900/80 to-background",
  },
  {
    id: 'tech-6',
    topicId: 'technology',
    title: "One-click purchases exploit impulses.",
    content: "The easier buying is, the more impulsive it becomes. Adding friction (like removing saved payment) reduces regret purchases.",
    fact: "Adding a 24-hour wait reduces impulse purchases by 40%.",
    imageUrl: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=600&fit=crop",
    gradient: "from-amber-900/90 via-orange-900/80 to-background",
  },
  {
    id: 'tech-7',
    topicId: 'technology',
    title: "The like button was designed to addict.",
    content: "Social validation triggers dopamine. The like button creator regrets what it's done to attention and self-worth.",
    fact: "Brain scans show likes activate the same areas as money and food.",
    imageUrl: "https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=800&h=600&fit=crop",
    gradient: "from-pink-900/90 via-rose-900/80 to-background",
  },
  {
    id: 'tech-8',
    topicId: 'technology',
    title: "Digital minimalism works.",
    content: "Intentionally choosing which technologies to use — and for what purpose — increases life satisfaction.",
    fact: "People who audit their digital tools report feeling less overwhelmed.",
    tryThis: "Delete one app you use mindlessly for a week.",
    imageUrl: "https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=800&h=600&fit=crop",
    gradient: "from-teal-900/90 via-cyan-900/80 to-background",
  },

  // ==================== RELATIONSHIPS (8 cards) ====================
  {
    id: 'rel-1',
    topicId: 'relationships',
    title: "Connection is a basic need.",
    content: "Loneliness activates the same brain regions as physical pain. Real relationships — not parasocial ones — are essential.",
    fact: "Strong relationships are the #1 predictor of happiness.",
    imageUrl: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&h=600&fit=crop",
    gradient: "from-red-900/90 via-pink-900/80 to-background",
  },
  {
    id: 'rel-2',
    topicId: 'relationships',
    title: "Screens replace face time.",
    content: "Hours spent on devices often subtract from in-person connection. The brain knows the difference.",
    fact: "Face-to-face interaction releases oxytocin; screens don't.",
    tryThis: "Replace 30 mins of screen time with a call or hangout.",
    imageUrl: "https://images.unsplash.com/photo-1543807535-eceef0bc6599?w=800&h=600&fit=crop",
    gradient: "from-pink-900/90 via-rose-900/80 to-background",
  },
  {
    id: 'rel-3',
    topicId: 'relationships',
    title: "Vulnerability builds connection.",
    content: "Deep relationships require showing your real self. Vulnerability is not weakness — it's the birthplace of trust.",
    fact: "People who show vulnerability are rated as more likeable.",
    imageUrl: "https://images.unsplash.com/photo-1516733968668-dbdce39c4651?w=800&h=600&fit=crop",
    gradient: "from-purple-900/90 via-violet-900/80 to-background",
  },
  {
    id: 'rel-4',
    topicId: 'relationships',
    title: "Quality over quantity.",
    content: "A few deep relationships matter more than many shallow ones. Invest in the relationships that matter most.",
    fact: "Most people can only maintain 5 close relationships at once.",
    imageUrl: "https://images.unsplash.com/photo-1536010305525-f7aa0834e2c7?w=800&h=600&fit=crop",
    gradient: "from-blue-900/90 via-indigo-900/80 to-background",
  },
  {
    id: 'rel-5',
    topicId: 'relationships',
    title: "Listening is an underrated skill.",
    content: "Most people listen to respond, not to understand. True listening — without planning your reply — is rare and powerful.",
    fact: "People remember how you made them feel more than what you said.",
    tryThis: "In your next conversation, just listen. Don't plan your response.",
    imageUrl: "https://images.unsplash.com/photo-1573497620053-ea5300f94f21?w=800&h=600&fit=crop",
    gradient: "from-teal-900/90 via-cyan-900/80 to-background",
  },
  {
    id: 'rel-6',
    topicId: 'relationships',
    title: "Conflict avoidance backfires.",
    content: "Avoiding difficult conversations creates distance. Healthy conflict, handled well, actually strengthens bonds.",
    fact: "Couples who never fight often have higher divorce rates.",
    imageUrl: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800&h=600&fit=crop",
    gradient: "from-amber-900/90 via-orange-900/80 to-background",
  },
  {
    id: 'rel-7',
    topicId: 'relationships',
    title: "Comparison steals joy.",
    content: "Social media shows highlight reels, not real life. Comparing your inside to others' outside breeds dissatisfaction.",
    fact: "Social media use correlates with increased loneliness.",
    imageUrl: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=600&fit=crop",
    gradient: "from-rose-900/90 via-red-900/80 to-background",
  },
  {
    id: 'rel-8',
    topicId: 'relationships',
    title: "Presence is the gift.",
    content: "Being fully present with someone is increasingly rare and valuable. Put the phone away when you're with people.",
    fact: "Phone presence (even face-down) reduces connection quality.",
    tryThis: "Phone away during your next meal with someone.",
    imageUrl: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&h=600&fit=crop",
    gradient: "from-green-900/90 via-emerald-900/80 to-background",
  },

  // ==================== CREATIVITY (8 cards) ====================
  {
    id: 'create-1',
    topicId: 'creativity',
    title: "Consumption kills creation.",
    content: "When you're constantly consuming (scrolling, watching), you have no mental space to create. Creation is where meaning lives.",
    fact: "Boredom is the birthplace of creativity.",
    tryThis: "Spend 20 minutes creating something today.",
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=600&fit=crop",
    gradient: "from-fuchsia-900/90 via-purple-900/80 to-background",
  },
  {
    id: 'create-2',
    topicId: 'creativity',
    title: "Flow state is the goal.",
    content: "Deep engagement in challenging work produces 'flow' — a state of effortless focus and fulfillment. Scrolling can't produce this.",
    fact: "Flow activates dopamine without the crash.",
    imageUrl: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&h=600&fit=crop",
    gradient: "from-violet-900/90 via-indigo-900/80 to-background",
  },
  {
    id: 'create-3',
    topicId: 'creativity',
    title: "Creativity needs constraints.",
    content: "Unlimited options paralyze creativity. Constraints force innovation. Give yourself boundaries and see what happens.",
    fact: "Twitter's character limit spawned new forms of writing.",
    tryThis: "Create something with an arbitrary constraint today.",
    imageUrl: "https://images.unsplash.com/photo-1456324504439-367cee3b3c32?w=800&h=600&fit=crop",
    gradient: "from-blue-900/90 via-cyan-900/80 to-background",
  },
  {
    id: 'create-4',
    topicId: 'creativity',
    title: "Bad work leads to good work.",
    content: "You can't edit a blank page. Create badly first. Refinement comes later. Perfectionism is the enemy of progress.",
    fact: "Prolific creators produce more good AND bad work than others.",
    imageUrl: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?w=800&h=600&fit=crop",
    gradient: "from-rose-900/90 via-pink-900/80 to-background",
  },
  {
    id: 'create-5',
    topicId: 'creativity',
    title: "Incubation is part of the process.",
    content: "Step away from problems. Your unconscious continues working. Many breakthroughs come after rest, not during effort.",
    fact: "Sleep helps consolidate creative insights.",
    imageUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=800&h=600&fit=crop",
    gradient: "from-indigo-900/90 via-blue-900/80 to-background",
  },
  {
    id: 'create-6',
    topicId: 'creativity',
    title: "Cross-pollination sparks ideas.",
    content: "The best ideas often come from combining concepts from different fields. Read widely. Talk to people unlike you.",
    fact: "Many innovations come from outsiders, not experts.",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop",
    gradient: "from-amber-900/90 via-orange-900/80 to-background",
  },
  {
    id: 'create-7',
    topicId: 'creativity',
    title: "Morning pages unlock creativity.",
    content: "Writing 3 pages of stream-of-consciousness first thing clears mental clutter and often reveals hidden insights.",
    fact: "Julia Cameron's technique has helped millions of creators.",
    tryThis: "Write 3 pages first thing tomorrow, no editing.",
    imageUrl: "https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop",
    gradient: "from-green-900/90 via-emerald-900/80 to-background",
  },
  {
    id: 'create-8',
    topicId: 'creativity',
    title: "Ship before you're ready.",
    content: "Perfection is procrastination in disguise. Put your work out there. You'll learn more from feedback than from polishing.",
    fact: "Most successful products launched 'before they were ready.'",
    imageUrl: "https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?w=800&h=600&fit=crop",
    gradient: "from-teal-900/90 via-cyan-900/80 to-background",
  },

  // ==================== PHILOSOPHY (8 cards) ====================
  {
    id: 'phil-1',
    topicId: 'philosophy',
    title: "Pleasure ≠ Happiness.",
    content: "Ancient philosophers knew: pleasure is fleeting, meaning is lasting. Dopamine hits feel good but don't add up to a good life.",
    fact: "Aristotle called this 'eudaimonia' — flourishing through purpose.",
    imageUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=800&h=600&fit=crop",
    gradient: "from-indigo-900/90 via-blue-900/80 to-background",
  },
  {
    id: 'phil-2',
    topicId: 'philosophy',
    title: "You're not your thoughts.",
    content: "Mindfulness teaches: thoughts and urges arise, but you choose whether to follow them. You are the observer, not the thought.",
    fact: "This is the foundation of cognitive behavioral therapy.",
    tryThis: "Watch your next urge like you're watching clouds pass.",
    imageUrl: "https://images.unsplash.com/photo-1528722828814-77b9b83aafb2?w=800&h=600&fit=crop",
    gradient: "from-purple-900/90 via-violet-900/80 to-background",
  },
  {
    id: 'phil-3',
    topicId: 'philosophy',
    title: "Memento mori: remember death.",
    content: "Contemplating mortality clarifies priorities. Stoics used this to focus on what truly matters.",
    fact: "Regular death contemplation correlates with decreased anxiety.",
    imageUrl: "https://images.unsplash.com/photo-1501139083538-0139583c060f?w=800&h=600&fit=crop",
    gradient: "from-slate-900/90 via-gray-900/80 to-background",
  },
  {
    id: 'phil-4',
    topicId: 'philosophy',
    title: "You control only your response.",
    content: "Stoicism's core insight: you can't control events, only your reactions. Focus energy there, not on what you can't change.",
    fact: "Viktor Frankl survived Auschwitz by focusing on what he could control.",
    imageUrl: "https://images.unsplash.com/photo-1474418397713-7ede21d49118?w=800&h=600&fit=crop",
    gradient: "from-blue-900/90 via-indigo-900/80 to-background",
  },
  {
    id: 'phil-5',
    topicId: 'philosophy',
    title: "The examined life is worth living.",
    content: "Socrates argued that self-reflection is essential to a good life. Understanding yourself is the beginning of wisdom.",
    fact: "Regular self-reflection improves decision-making.",
    tryThis: "Ask yourself: 'Why did I do that?'",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop",
    gradient: "from-amber-900/90 via-orange-900/80 to-background",
  },
  {
    id: 'phil-6',
    topicId: 'philosophy',
    title: "Suffering often comes from attachment.",
    content: "Buddhist philosophy: clinging to outcomes causes suffering. Acceptance of impermanence brings peace.",
    fact: "Mindfulness practices derived from this reduce anxiety.",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop",
    gradient: "from-teal-900/90 via-cyan-900/80 to-background",
  },
  {
    id: 'phil-7',
    topicId: 'philosophy',
    title: "The present is all that exists.",
    content: "The past is memory; the future is imagination. Only now is real. Most suffering comes from living in past or future.",
    fact: "Presence is trainable through consistent practice.",
    imageUrl: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=800&h=600&fit=crop",
    gradient: "from-rose-900/90 via-pink-900/80 to-background",
  },
  {
    id: 'phil-8',
    topicId: 'philosophy',
    title: "Virtue is its own reward.",
    content: "Acting according to your values creates inner peace regardless of outcomes. Character is built through consistent action.",
    fact: "People with clear values report higher life satisfaction.",
    imageUrl: "https://images.unsplash.com/photo-1455849318743-b2233052fcff?w=800&h=600&fit=crop",
    gradient: "from-green-900/90 via-emerald-900/80 to-background",
  },

  // ==================== HISTORY (10 cards) ====================
  {
    id: 'hist-1',
    topicId: 'history',
    title: "Rome wasn't built in a day.",
    content: "The Roman Empire took centuries to build and centuries to fall. Great achievements require sustained effort over time.",
    fact: "Rome went from village to empire over 500+ years.",
    imageUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&h=600&fit=crop",
    gradient: "from-amber-900/90 via-yellow-900/80 to-background",
  },
  {
    id: 'hist-2',
    topicId: 'history',
    title: "The Library of Alexandria.",
    content: "The ancient world's greatest library held hundreds of thousands of scrolls — much of human knowledge. Its loss reminds us knowledge is fragile.",
    fact: "We've lost 90%+ of ancient literature.",
    imageUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&h=600&fit=crop",
    gradient: "from-orange-900/90 via-amber-900/80 to-background",
  },
  {
    id: 'hist-3',
    topicId: 'history',
    title: "Empires rise and fall.",
    content: "Every great civilization eventually declined. The patterns repeat: growth, overextension, decay. History is cyclical.",
    fact: "The average lifespan of an empire is about 250 years.",
    imageUrl: "https://images.unsplash.com/photo-1564769625905-50e93615e769?w=800&h=600&fit=crop",
    gradient: "from-rose-900/90 via-red-900/80 to-background",
  },
  {
    id: 'hist-4',
    topicId: 'history',
    title: "The Renaissance changed everything.",
    content: "After centuries of stagnation, Europe rediscovered classical learning. It shows how ideas can transform societies.",
    fact: "The printing press accelerated the Renaissance exponentially.",
    tryThis: "What 'old' ideas might transform your life if rediscovered?",
    imageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop",
    gradient: "from-blue-900/90 via-indigo-900/80 to-background",
  },
  {
    id: 'hist-5',
    topicId: 'history',
    title: "The Stoics were onto something.",
    content: "Marcus Aurelius ruled Rome while practicing Stoic philosophy. His Meditations, written for himself, still guide people 2000 years later.",
    fact: "Marcus Aurelius never intended his journal to be published.",
    imageUrl: "https://images.unsplash.com/photo-1575936123452-b67c3203c357?w=800&h=600&fit=crop",
    gradient: "from-slate-900/90 via-gray-900/80 to-background",
  },
  {
    id: 'hist-6',
    topicId: 'history',
    title: "The Black Death reshaped society.",
    content: "The plague killed 1/3 of Europe but led to better wages for survivors and weakened feudalism. Crisis creates opportunity.",
    fact: "Labor shortages after the plague empowered workers.",
    imageUrl: "https://images.unsplash.com/photo-1546198632-9ef6368bef12?w=800&h=600&fit=crop",
    gradient: "from-purple-900/90 via-violet-900/80 to-background",
  },
  {
    id: 'hist-7',
    topicId: 'history',
    title: "The Industrial Revolution changed time itself.",
    content: "Before factories, people worked by the sun. Industrialization introduced clock-time, transforming how we experience life.",
    fact: "Standardized time zones were created for train schedules.",
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=600&fit=crop",
    gradient: "from-cyan-900/90 via-teal-900/80 to-background",
  },
  {
    id: 'hist-8',
    topicId: 'history',
    title: "History's greatest minds doubted themselves.",
    content: "Lincoln was depressed. Newton had breakdowns. Van Gogh sold one painting. Greatness doesn't require constant confidence.",
    fact: "Many geniuses were only recognized after death.",
    imageUrl: "https://images.unsplash.com/photo-1569172122301-bc5008bc09c5?w=800&h=600&fit=crop",
    gradient: "from-yellow-900/90 via-amber-900/80 to-background",
  },
  {
    id: 'hist-9',
    topicId: 'history',
    title: "Civilizations collapse from within.",
    content: "Most empires fell not from invasion but from internal decay: corruption, inequality, loss of civic virtue. The enemy is often inside.",
    fact: "Rome's fall took 300 years and happened gradually.",
    imageUrl: "https://images.unsplash.com/photo-1555992336-fb0d29498b13?w=800&h=600&fit=crop",
    gradient: "from-red-900/90 via-rose-900/80 to-background",
  },
  {
    id: 'hist-10',
    topicId: 'history',
    title: "Information technology always disrupts.",
    content: "Writing, printing, internet — each information revolution transformed society. We're living through another one right now.",
    fact: "Socrates worried writing would destroy memory. Sound familiar?",
    tryThis: "What would past humans think of your daily information diet?",
    imageUrl: "https://images.unsplash.com/photo-1456324504439-367cee3b3c32?w=800&h=600&fit=crop",
    gradient: "from-indigo-900/90 via-blue-900/80 to-background",
  },
];

// Utility functions
export function getCardsByTopics(topicIds: string[]): LearnCard[] {
  if (topicIds.length === 0) return LEARN_CARDS;
  return LEARN_CARDS.filter(card => topicIds.includes(card.topicId));
}

export function shuffleCards(cards: LearnCard[]): LearnCard[] {
  const shuffled = [...cards];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

export function getTopicById(id: string): LearnTopic | undefined {
  return LEARN_TOPICS.find(t => t.id === id);
}

// Local storage keys
export const LEARN_STORAGE_KEYS = {
  selectedTopics: 'learn-selected-topics',
  hasSeenIntro: 'learn-has-seen-intro',
  likedCards: 'learn-liked-cards',
  hiddenCards: 'learn-hidden-cards',
} as const;
